name: quai-antique-app
type: php:8.2

# Build et déploiement
build:
    flavor: composer
    hooks:
        pre-deploy:
            # Installer les dépendances et optimiser l'autoloader
            - composer install --no-dev --optimize-autoloader
            # Clear et warmup le cache Symfony pour prod
            - php bin/console cache:clear --env=prod
            - php bin/console cache:warmup --env=prod

# Variables d'environnement
variables:
    env:
        APP_ENV: prod
        APP_DEBUG: 0
        DATABASE_URL: "mysql://user:password@db-main.aofzto4ibqmv2.platformsh.site:3306/Quai_Antique?serverVersion=10.4.28-mariadb&charset=utf8mb4"

# Application web
web:
    locations:
        "/":
            root: "public"
            index: ["index.php"]
            allow: true
    scripts:
        # Point d'entrée pour le serveur web
        start: "php-fpm"
