name: app
type: "php:8.2"
disk: 1024

# Variables d'environnement
variables:
    env:
        APP_ENV: "prod"
        APP_DEBUG: "0"
        APP_SECRET: "change_this_secret"
        DATABASE_URL: "mysql://{user}:{password}@{host}:{port}/{database}?serverVersion=10.4&charset=utf8mb4"

# Web server
web:
    locations:
        "/":
            root: "public"
            index: ["index.php"]
            allow: true

# Build & deploy hooks
hooks:
    build: |
        set -e
        composer install --no-dev --optimize-autoloader
    deploy: |
        php bin/console cache:clear --env=prod
        php bin/console doctrine:migrations:migrate --no-interaction
