name: app
type: "php:8.2"
disk: 2048

variables:
    env:
        APP_ENV: "prod"
        APP_DEBUG: "0"
        APP_SECRET: "CHANGE_ME"
        # IMPORTANT : on met serverVersion=10.4 pour MariaDB 10.4
        DATABASE_URL: "mysql://{user}:{password}@{host}:{port}/{database}?serverVersion=mariadb-10.4&charset=utf8mb4"

web:
    locations:
        "/":
            root: "public"
            index: ["index.php"]
            allow: true

dependencies:
    php:
        composer/composer: "^2"

build:
    flavor: composer

hooks:
    build: |
        set -e
        composer install --no-dev --optimize-autoloader

    deploy: |
        php bin/console cache:clear --env=prod
        php bin/console doctrine:migrations:migrate --no-interaction
