name: symfony
type: php:8.3
build:
    flavor: none

dependencies:
    php:
        composer/composer: "^2.5"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
