name: symfony
type: php:8.3
build:
    flavor: none

dependencies:
    php:
        composer/composer: "^2.5"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
relational:
    database: "mysql:mysql"

mounts:
    "var/log": "shared:files/log"
    "var/cache": "shared:files/cache"
    "public/uploads": "shared:files/uploads"

runtime:
    extensions:
        - mbstring
        - pdo
        - pdo_mysql
        - intl
        - opcache
