<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Booking__CLASSMETADATA__' => 0,
'App__Entity__Category__CLASSMETADATA__' => 1,
'App__Entity__Food__CLASSMETADATA__' => 2,
'App__Entity__FoodCategory__CLASSMETADATA__' => 3,
'App__Entity__Menu__CLASSMETADATA__' => 4,
'App__Entity__MenuCategory__CLASSMETADATA__' => 5,
'App__Entity__Picture__CLASSMETADATA__' => 6,
'App__Entity__Restaurant__CLASSMETADATA__' => 7,
'App__Entity__User__CLASSMETADATA__' => 8,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Booking',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\BookingRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'guestNumber' => $o[2],
                    'orderDate' => $o[3],
                    'allergy' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'guest_number' => 'guestNumber',
                    'order_date' => 'orderDate',
                    'allergy' => 'allergy',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'guestNumber' => 'guest_number',
                    'orderDate' => 'order_date',
                    'allergy' => 'allergy',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'booking',
                ],
            ],
            'associationMappings' => [
                [
                    'Restaurant' => $o[7],
                    'client' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[11],
            ],
            'name' => [
                'App\\Entity\\Booking',
                8 => 'restaurant_id',
                10 => 'client_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'date',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'guestNumber',
                'orderDate',
                'allergy',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'guest_number',
                'order_date',
                'allergy',
                'created_at',
                'updated_at',
            ],
            'length' => [
                4 => 255,
            ],
            'nullable' => [
                4 => true,
                6 => true,
                8 => false,
                10 => false,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Booking',
                9 => 'App\\Entity\\Booking',
            ],
            'inversedBy' => [
                7 => 'bookings',
                9 => 'bookings',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'restaurant_id' => 'id',
                ],
                9 => [
                    'client_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'restaurant_id',
                ],
                9 => [
                    'id' => 'client_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
                9 => [
                    $o[10],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'restaurant_id' => 'restaurant_id',
                ],
                9 => [
                    'client_id' => 'client_id',
                ],
            ],
            'deferrable' => [
                8 => false,
                10 => false,
            ],
            'unique' => [
                8 => false,
                10 => false,
            ],
            'referencedColumnName' => [
                8 => 'id',
                10 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'Restaurant',
                9 => 'client',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Restaurant',
                9 => 'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Category',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CategoryRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'createdAt' => $o[3],
                    'updatedAt' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'category',
                ],
            ],
            'associationMappings' => [
                [
                    'menuCategories' => $o[5],
                    'foodCategories' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\Category',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 64,
            ],
            'nullable' => [
                4 => true,
            ],
            'fetch' => [
                5 => 2,
                2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Category',
                'App\\Entity\\Category',
            ],
            'mappedBy' => [
                5 => 'CategoryId',
                'CategoryId',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'menuCategories',
                'foodCategories',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\MenuCategory',
                'App\\Entity\\FoodCategory',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Food',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\FoodRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'description' => $o[3],
                    'price' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'food',
                ],
            ],
            'associationMappings' => [
                [
                    'foodCategories' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Food',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'integer',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 64,
            ],
            'nullable' => [
                6 => true,
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Food',
            ],
            'mappedBy' => [
                7 => 'FoodId',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'foodCategories',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\FoodCategory',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\FoodCategory',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\FoodCategoryRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                ],
            ],
            'table' => [
                [
                    'name' => 'food_category',
                ],
            ],
            'associationMappings' => [
                [
                    'FoodId' => $o[2],
                    'CategoryId' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\FoodCategory',
                3 => 'food_id_id',
                5 => 'category_id_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
            ],
            'fieldName' => [
                1 => 'id',
            ],
            'columnName' => [
                1 => 'id',
            ],
            'fetch' => [
                2 => 2,
                4 => 2,
            ],
            'sourceEntity' => [
                2 => 'App\\Entity\\FoodCategory',
                4 => 'App\\Entity\\FoodCategory',
            ],
            'inversedBy' => [
                2 => 'foodCategories',
                4 => 'foodCategories',
            ],
            'sourceToTargetKeyColumns' => [
                2 => [
                    'food_id_id' => 'id',
                ],
                4 => [
                    'category_id_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                2 => [
                    'id' => 'food_id_id',
                ],
                4 => [
                    'id' => 'category_id_id',
                ],
            ],
            'joinColumns' => [
                2 => [
                    $o[3],
                ],
                4 => [
                    $o[5],
                ],
            ],
            'joinColumnFieldNames' => [
                2 => [
                    'food_id_id' => 'food_id_id',
                ],
                4 => [
                    'category_id_id' => 'category_id_id',
                ],
            ],
            'nullable' => [
                3 => true,
                5 => true,
            ],
            'referencedColumnName' => [
                3 => 'id',
                5 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                2 => 'FoodId',
                4 => 'CategoryId',
            ],
            'targetEntity' => [
                2 => 'App\\Entity\\Food',
                4 => 'App\\Entity\\Category',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Menu',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\MenuRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'description' => $o[3],
                    'price' => $o[4],
                    'createdAt' => $o[5],
                    'updatedat' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'created_at' => 'createdAt',
                    'updatedat' => 'updatedat',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'description' => 'description',
                    'price' => 'price',
                    'createdAt' => 'created_at',
                    'updatedat' => 'updatedat',
                ],
            ],
            'table' => [
                [
                    'name' => 'menu',
                ],
            ],
            'associationMappings' => [
                [
                    'Restaurant' => $o[7],
                    'menuCategories' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Menu',
                8 => 'restaurant_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'integer',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'createdAt',
                'updatedat',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'description',
                'price',
                'created_at',
                'updatedat',
            ],
            'length' => [
                2 => 64,
            ],
            'nullable' => [
                6 => true,
                8 => false,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Menu',
                9 => 'App\\Entity\\Menu',
            ],
            'inversedBy' => [
                7 => 'menus',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'restaurant_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'restaurant_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'restaurant_id' => 'restaurant_id',
                ],
            ],
            'deferrable' => [
                8 => false,
            ],
            'unique' => [
                8 => false,
            ],
            'referencedColumnName' => [
                8 => 'id',
            ],
            'mappedBy' => [
                9 => 'MenuId',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'Restaurant',
                9 => 'menuCategories',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Restaurant',
                9 => 'App\\Entity\\MenuCategory',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\MenuCategory',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\MenuCategoryRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                ],
            ],
            'table' => [
                [
                    'name' => 'menu_category',
                ],
            ],
            'associationMappings' => [
                [
                    'MenuId' => $o[2],
                    'CategoryId' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\MenuCategory',
                3 => 'menu_id_id',
                5 => 'category_id_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
            ],
            'fieldName' => [
                1 => 'id',
            ],
            'columnName' => [
                1 => 'id',
            ],
            'fetch' => [
                2 => 2,
                4 => 2,
            ],
            'sourceEntity' => [
                2 => 'App\\Entity\\MenuCategory',
                4 => 'App\\Entity\\MenuCategory',
            ],
            'inversedBy' => [
                2 => 'menuCategories',
                4 => 'menuCategories',
            ],
            'sourceToTargetKeyColumns' => [
                2 => [
                    'menu_id_id' => 'id',
                ],
                4 => [
                    'category_id_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                2 => [
                    'id' => 'menu_id_id',
                ],
                4 => [
                    'id' => 'category_id_id',
                ],
            ],
            'joinColumns' => [
                2 => [
                    $o[3],
                ],
                4 => [
                    $o[5],
                ],
            ],
            'joinColumnFieldNames' => [
                2 => [
                    'menu_id_id' => 'menu_id_id',
                ],
                4 => [
                    'category_id_id' => 'category_id_id',
                ],
            ],
            'nullable' => [
                3 => true,
                5 => true,
            ],
            'referencedColumnName' => [
                3 => 'id',
                5 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                2 => 'MenuId',
                4 => 'CategoryId',
            ],
            'targetEntity' => [
                2 => 'App\\Entity\\Menu',
                4 => 'App\\Entity\\Category',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Picture',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PictureRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'slug' => $o[3],
                    'createdAt' => $o[4],
                    'updatedAt' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'title' => 'title',
                    'slug' => 'slug',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'picture',
                ],
            ],
            'associationMappings' => [
                [
                    'restaurant' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Picture',
                7 => 'restaurant_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'title',
                'slug',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'title',
                'slug',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 64,
                64,
            ],
            'nullable' => [
                5 => true,
                7 => false,
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Picture',
            ],
            'inversedBy' => [
                6 => 'pictures',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'restaurant_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id' => 'restaurant_id',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'restaurant_id' => 'restaurant_id',
                ],
            ],
            'deferrable' => [
                7 => false,
            ],
            'unique' => [
                7 => false,
            ],
            'referencedColumnName' => [
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'restaurant',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Restaurant',
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Restaurant',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\RestaurantRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'description' => $o[3],
                    'amOpeningTime' => $o[4],
                    'pmOpeningTime' => $o[5],
                    'max_guest' => $o[6],
                    'createdAt' => $o[7],
                    'updatedAt' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'am_opening_time' => 'amOpeningTime',
                    'pm_opening_time' => 'pmOpeningTime',
                    'max_guest' => 'max_guest',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'amOpeningTime' => 'am_opening_time',
                    'pmOpeningTime' => 'pm_opening_time',
                    'max_guest' => 'max_guest',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'restaurant',
                ],
            ],
            'associationMappings' => [
                [
                    'pictures' => $o[9],
                    'bookings' => $o[10],
                    'menus' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\Restaurant',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'json',
                'json',
                'integer',
                'datetime_immutable',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'description',
                'amOpeningTime',
                'pmOpeningTime',
                'max_guest',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'description',
                'am_opening_time',
                'pm_opening_time',
                'max_guest',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 32,
            ],
            'nullable' => [
                6 => true,
                8 => true,
            ],
            'cascade' => [
                9 => [
                    'remove',
                ],
                [
                    'remove',
                ],
                [
                    'remove',
                ],
            ],
            'fetch' => [
                9 => 2,
                2,
                2,
            ],
            'orphanRemoval' => [
                9 => true,
                true,
                true,
            ],
            'sourceEntity' => [
                9 => 'App\\Entity\\Restaurant',
                'App\\Entity\\Restaurant',
                'App\\Entity\\Restaurant',
            ],
            'mappedBy' => [
                9 => 'restaurant',
                'Restaurant',
                'Restaurant',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                9 => 'pictures',
                'bookings',
                'menus',
            ],
            'targetEntity' => [
                9 => 'App\\Entity\\Picture',
                'App\\Entity\\Booking',
                'App\\Entity\\Menu',
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                    'apiToken' => $o[7],
                    'firstName' => $o[8],
                    'lastName' => $o[9],
                    'guestNumber' => $o[10],
                    'allergy' => $o[11],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                    'api_token' => 'apiToken',
                    'first_name' => 'firstName',
                    'last_name' => 'lastName',
                    'guest_number' => 'guestNumber',
                    'allergy' => 'allergy',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                    'apiToken' => 'api_token',
                    'firstName' => 'first_name',
                    'lastName' => 'last_name',
                    'guestNumber' => 'guest_number',
                    'allergy' => 'allergy',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'uniqueConstraints' => [
                        'UNIQ_IDENTIFIER_EMAIL' => [
                            'fields' => [
                                'email',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'string',
                'datetime_immutable',
                'datetime_immutable',
                'string',
                'string',
                'string',
                'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'createdAt',
                'updatedAt',
                'apiToken',
                'firstName',
                'lastName',
                'guestNumber',
                'allergy',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'created_at',
                'updated_at',
                'api_token',
                'first_name',
                'last_name',
                'guest_number',
                'allergy',
            ],
            'length' => [
                2 => 180,
                7 => 255,
                32,
                64,
                11 => 255,
            ],
            'nullable' => [
                6 => true,
                10 => true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
