<?php

namespace ContainerFvtJu1M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTokenAuthenticatorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Security\ApiTokenAuthenticator' shared autowired service.
     *
     * @return \App\Security\ApiTokenAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\ApiTokenAuthenticator'] = new \App\Security\ApiTokenAuthenticator(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
