<?php

namespace ContainerFvtJu1M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader();
        $a->addFixtures([['fixture' => new \App\DataFixtures\AppFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\BookingFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\CategoryFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\FoodCategoryFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\FoodFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\MenuCategoryFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\MenuFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\PictureFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\RestaurantFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\UserFixtures(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($container->services['doctrine'] ?? $container->load('getDoctrineService')), ['default' => new \Doctrine\Bundle\FixturesBundle\Purger\ORMPurgerFactory()]);

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
