<?php

namespace ContainerFvtJu1M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\FoodRepository' shared autowired service.
     *
     * @return \App\Repository\FoodRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FoodRepository'] = new \App\Repository\FoodRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
