<?php

namespace ContainerFvtJu1M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevContainer
{
    /*
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'API Documentation', 'description' => 'Documentation de l\'API restaurant Studi', 'version' => '1.0.0'], 'components' => ['securitySchemes' => ['X-AUTH-TOKEN' => ['type' => 'apiKey', 'name' => 'X-AUTH-TOKEN', 'in' => 'header']]], 'security' => [['X-AUTH-TOKEN' => []]]]);
    }
}
