<?php

namespace ContainerFvtJu1M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPictureRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\PictureRepository' shared autowired service.
     *
     * @return \App\Repository\PictureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PictureRepository'] = new \App\Repository\PictureRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
