<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOzCX8S7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOzCX8S7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOzCX8S7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOzCX8S7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOzCX8S7\App_KernelProdContainer([
    'container.build_hash' => 'OzCX8S7',
    'container.build_id' => 'bd41a59a',
    'container.build_time' => 1768398169,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOzCX8S7');
