# .upsun/project.yaml

applications:
    app:
        type: php:8.2

        build:
            flavor: none

        web:
            locations:
                "/":
                    root: "public"
                    index: ["index.php"]
                    allow: true
                    scripts: true
                    passthru: "/index.php"

        dependencies:
            php:
                composer/composer: "^2"

        runtime:
            extensions:
                - mbstring
                - pdo
                - pdo_mysql
                - intl
                - opcache

        # Relation vers le service MySQL défini ci-dessous
        relationships:
            database: "mysql:mysql"

# Définition du service MySQL directement dans project.yaml
services:
    mysql:
        type: mariadb:10.4
