applications:
    app:
        type: php:8.2
        build:
            flavor: none

        web:
            locations:
                "/":
                    root: "public"
                    index: ["index.php"]
                    allow: true
                    scripts: true
                    passthru: "/index.php"

        dependencies:
            php:
                composer/composer: "^2"

        runtime:
            extensions:
                - mbstring
                - pdo
                - pdo_mysql
                - intl
                - opcache

        relationships:
            database: "mysql:mysql" # alias:nom_service exact
