<?php

namespace ContainerTHUho1i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_EventManagerDebugCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'doctrine.event_manager_debug_command' shared service.
     *
     * @return \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.event_manager_debug_command'] = $instance = new \Doctrine\ORM\Tools\Console\Command\Debug\DebugEventManagerDoctrineCommand(($container->services['doctrine'] ?? $container->load('getDoctrineService')));

        $instance->setName('doctrine:debug:event-manager');

        return $instance;
    }
}
