<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBqtmUCx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBqtmUCx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBqtmUCx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBqtmUCx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBqtmUCx\App_KernelProdContainer([
    'container.build_hash' => 'BqtmUCx',
    'container.build_id' => '68e01b81',
    'container.build_time' => 1768398053,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBqtmUCx');
