<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLRKwHlq\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLRKwHlq/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLRKwHlq.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLRKwHlq\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLRKwHlq\App_KernelProdContainer([
    'container.build_hash' => 'LRKwHlq',
    'container.build_id' => '0c2c20fc',
    'container.build_time' => 1768470726,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLRKwHlq');
