<?php

namespace ContainerBqtmUCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFamilyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FamilyRepository' shared autowired service.
     *
     * @return \App\Repository\FamilyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FamilyRepository'] = new \App\Repository\FamilyRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
