<?php

namespace ContainerOzCX8S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodCategoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FoodCategoryRepository' shared autowired service.
     *
     * @return \App\Repository\FoodCategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FoodCategoryRepository'] = new \App\Repository\FoodCategoryRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
