<?php

namespace ContainerOzCX8S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FoodController' shared autowired service.
     *
     * @return \App\Controller\FoodController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FoodController'] = $instance = new \App\Controller\FoodController(($container->privates['App\\Repository\\FoodRepository'] ?? $container->load('getFoodRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\FoodController', $container));

        return $instance;
    }
}
