<?php

namespace ContainerLRKwHlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BookingController' shared autowired service.
     *
     * @return \App\Controller\BookingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BookingController'] = $instance = new \App\Controller\BookingController(($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\BookingController', $container));

        return $instance;
    }
}
