<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvtJu1M\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvtJu1M/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerFvtJu1M.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerFvtJu1M\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerFvtJu1M\App_KernelDevContainer([
    'container.build_hash' => 'FvtJu1M',
    'container.build_id' => 'fc3a4c2b',
    'container.build_time' => 1768470800,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvtJu1M');
